### ISSUE TITLE
Problems and Suggestions

### ISSUE THREAD

**Issue by 19steind** [erikwoods/r-WorldOfNintendo#2]
You should fix the "other discussions" tab to go with rest of the nav because it isn't curved as seen here. 
![](http://i.imgur.com/IbJ8nmj.png)
Secondly, you should reduce the width of the comment outline when it goes past the sidebar so it doesn't look weird as seen here.
![](http://i.imgur.com/fLmjVQJ.png)
Thirdly, you should fix the Target flair so that it shows up.
Also, please add Blue Pikmin flair to use in contests.

**Comment by 19steind** [comment]
Also, in the mail section, there is a similar problem as with when there is another discussion.

**Comment by erikwoods** [comment]
Thanks @19steind - I will have to make all nav elements have the rounded corners or none of them. It's too flimsy to try to do it the way I was doing it. I'm glad you found this.

**Comment by erikwoods** [comment]
Please separate these things into several issues. One issue per... issue. Thx.

**Comment by erikwoods** [comment]
Nevermind about making new issues per issue for now. In the future, please put one issue per issue - don't put a bunch in one. It makes it harder to manage. For this time though I'll take care of all in one. Just means I can't close the issue until all are done.

PS Nav fixed.

**Comment by erikwoods** [comment]
@19steind:
* the nav has been fixed - we don't have many options so I went with the easiest and most future-proof option
* the width of comments has been adjusted
* Target flair is fine and works as expected
* I'll add more flair later. I don't think flair is incentive enough for users to enter contests.
