### ISSUE TITLE
Delete /u/amiibocustomsrus's Mod Flair

### ISSUE THREAD

**Issue by 19steind** [erikwoods/r-WorldOfNintendo#4]
He has been removed from mod due to abuse of power. He banned users and deleted posts and comments because he didn't like them, even though they were okay according to the rules.

**Comment by erikwoods** [comment]
Aight I will. Thanks bro.

**Comment by erikwoods** [comment]
Fixed via [https://github.com/erikwoods/r-WorldOfNintendo/commit/3cade5c74609c1646a7f56244d04d7be5f922fd2](https://github.com/erikwoods/r-WorldOfNintendo/commit/3cade5c74609c1646a7f56244d04d7be5f922fd2)
